### ISSUE TITLE
if any unknown user is in the frame it is assigning label to that face, how to overcome this issue?

### ISSUE THREAD

**Issue by bhagi1289** [mohitwildbeast/Facial-Recognition-Using-FaceNet-Siamese-One-Shot-Learning#1]

**Comment by mohitwildbeast** [comment]
I haven't figured out this issue. The code will assign some value to a similar-looking face in the database, hence the error. Suppose there are 2 faces, and an unknown face's distance  is closer to one, it will display the output.
